displayName=Better Brush Markers
author=ChronicOSRS
build=standard
support=https://github.com/ChronicOSRS/better-brush-markers
description= Get creative with your groundmarkers, now with import/export
tags= Artistic, Paint, Brush, Markers, Import, Export
plugins=com.bram91.brushmarkers.BrushMarkerPlugin
